import type { ProfessionPreset } from "./types";

/**
 * Profession presets.
 *
 * A preset is a starting point, not a cage: it picks a template, a colour
 * preset, a font pairing and the set of sections that profession usually needs.
 * Everything stays editable afterwards.
 */
export const PRESETS: ProfessionPreset[] = [
  {
    id: "developer",
    label: "Software Developer",
    icon: "Code2",
    description: "Projects, stack and experience — built for engineering hiring managers.",
    template: "sidebar",
    themePresetId: "slate",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    sections: ["hero", "about", "skills", "experience", "projects", "education", "contact"],
    profile: {
      headline: "Full-stack engineer",
      tagline: "I build fast, reliable web products end to end.",
      availability: "Open to work",
    },
  },
  {
    id: "designer",
    label: "Designer",
    icon: "Palette",
    description: "Visual-first layout that lets the work carry the page.",
    template: "canvas",
    themePresetId: "paper",
    headingFont: "Syne",
    bodyFont: "DM Sans",
    sections: ["hero", "gallery", "projects", "about", "services", "testimonials", "contact"],
    profile: {
      headline: "Product & brand designer",
      tagline: "Designing interfaces and identities that feel inevitable.",
      availability: "Taking new projects",
    },
  },
  {
    id: "photographer",
    label: "Photographer",
    icon: "Camera",
    description: "Full-bleed galleries with quiet typography and minimal chrome.",
    template: "canvas",
    themePresetId: "noir",
    headingFont: "Cormorant Garamond",
    bodyFont: "Montserrat",
    sections: ["hero", "gallery", "about", "services", "pricing", "testimonials", "contact"],
    profile: {
      headline: "Photographer",
      tagline: "Light, patience and the moment just before.",
      availability: "Booking 2026",
    },
  },
  {
    id: "writer",
    label: "Writer / Journalist",
    icon: "PenLine",
    description: "Editorial layout built around a body of published work.",
    template: "magazine",
    themePresetId: "paper",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    sections: ["hero", "about", "blog", "publications", "awards", "clients", "contact"],
    profile: {
      headline: "Writer and journalist",
      tagline: "Long-form reporting on technology, labour and cities.",
      availability: "Open to commissions",
    },
  },
  {
    id: "academic",
    label: "Academic / Researcher",
    icon: "GraduationCap",
    description: "Tabbed layout that keeps publications, teaching and grants separate.",
    template: "tabbed",
    themePresetId: "slate",
    headingFont: "EB Garamond",
    bodyFont: "Spectral",
    sections: ["hero", "about", "publications", "experience", "education", "awards", "languages", "contact"],
    profile: {
      headline: "Postdoctoral Researcher",
      tagline: "Distributed systems, fault tolerance and formal verification.",
      availability: "",
    },
  },
  {
    id: "doctor",
    label: "Doctor / Healthcare",
    icon: "Stethoscope",
    description: "Credentials, specialisms and practice details, clearly organised.",
    template: "tabbed",
    themePresetId: "arctic",
    headingFont: "Manrope",
    bodyFont: "Open Sans",
    sections: ["hero", "about", "services", "experience", "education", "certifications", "testimonials", "faq", "contact"],
    profile: {
      headline: "Consultant Cardiologist",
      tagline: "Evidence-led care, explained in plain language.",
      availability: "Accepting new patients",
    },
  },
  {
    id: "lawyer",
    label: "Lawyer",
    icon: "Scale",
    description: "Formal, credential-heavy layout that builds trust quickly.",
    template: "classic",
    themePresetId: "royal",
    headingFont: "Libre Baskerville",
    bodyFont: "Lato",
    sections: ["hero", "about", "services", "experience", "education", "awards", "testimonials", "faq", "contact"],
    profile: {
      headline: "Corporate & Commercial Lawyer",
      tagline: "Fifteen years advising founders, funds and boards.",
      availability: "",
    },
  },
  {
    id: "consultant",
    label: "Consultant",
    icon: "Compass",
    description: "Outcome-led page that leads with results and packages.",
    template: "bento",
    themePresetId: "slate",
    headingFont: "Manrope",
    bodyFont: "Inter",
    sections: ["hero", "stats", "services", "about", "clients", "testimonials", "pricing", "cta", "contact"],
    profile: {
      headline: "Operations consultant",
      tagline: "I help teams of 20–200 stop firefighting and start shipping.",
      availability: "Two slots open this quarter",
    },
  },
  {
    id: "student",
    label: "Student / Fresher",
    icon: "Backpack",
    description: "Education and projects first, for anyone early in their career.",
    template: "classic",
    themePresetId: "arctic",
    headingFont: "Outfit",
    bodyFont: "Nunito",
    sections: ["hero", "about", "education", "projects", "skills", "certifications", "languages", "contact"],
    profile: {
      headline: "Computer Science undergraduate",
      tagline: "Learning in public, shipping small things often.",
      availability: "Looking for internships",
    },
  },
  {
    id: "marketer",
    label: "Marketer",
    icon: "Megaphone",
    description: "Campaign results up front, with logos and numbers to back them.",
    template: "bento",
    themePresetId: "bubblegum",
    headingFont: "Bricolage Grotesque",
    bodyFont: "Work Sans",
    sections: ["hero", "stats", "about", "projects", "clients", "services", "testimonials", "contact"],
    profile: {
      headline: "Growth marketer",
      tagline: "Performance marketing that survives contact with a spreadsheet.",
      availability: "Open to consulting",
    },
  },
  {
    id: "musician",
    label: "Musician / Artist",
    icon: "Music",
    description: "Expressive, media-heavy page for performers and recording artists.",
    template: "onepage",
    themePresetId: "sunset",
    headingFont: "Unbounded",
    bodyFont: "Figtree",
    sections: ["hero", "about", "gallery", "custom", "blog", "testimonials", "contact"],
    profile: {
      headline: "Composer & performer",
      tagline: "Modular synths, tape loops and the space between.",
      availability: "Booking live dates",
    },
  },
  {
    id: "chef",
    label: "Chef / Hospitality",
    icon: "ChefHat",
    description: "Warm, appetising layout with menus, gallery and bookings.",
    template: "magazine",
    themePresetId: "sand",
    headingFont: "Fraunces",
    bodyFont: "Source Serif 4",
    sections: ["hero", "about", "gallery", "services", "pricing", "testimonials", "faq", "contact"],
    profile: {
      headline: "Private chef",
      tagline: "Seasonal menus cooked in your kitchen.",
      availability: "Booking private dinners",
    },
  },
  {
    id: "architect",
    label: "Architect",
    icon: "Ruler",
    description: "Project-led, drawing-friendly layout with a strong grid.",
    template: "canvas",
    themePresetId: "mono",
    headingFont: "Archivo Black",
    bodyFont: "Work Sans",
    sections: ["hero", "projects", "gallery", "about", "services", "awards", "clients", "contact"],
    profile: {
      headline: "Architect",
      tagline: "Buildings that age well and cost less to run.",
      availability: "",
    },
  },
  {
    id: "teacher",
    label: "Teacher / Coach",
    icon: "Presentation",
    description: "Approachable page focused on courses, outcomes and testimonials.",
    template: "classic",
    themePresetId: "forest",
    headingFont: "Figtree",
    bodyFont: "Nunito",
    sections: ["hero", "about", "services", "experience", "testimonials", "pricing", "faq", "contact"],
    profile: {
      headline: "Learning designer & coach",
      tagline: "Helping people get unstuck and keep going.",
      availability: "Taking students",
    },
  },
  {
    id: "datascientist",
    label: "Data Scientist",
    icon: "ChartSpline",
    description: "Research-flavoured layout with publications alongside applied work.",
    template: "timeline",
    themePresetId: "lagoon",
    headingFont: "Sora",
    bodyFont: "Inter",
    sections: ["hero", "about", "skills", "projects", "publications", "experience", "education", "contact"],
    profile: {
      headline: "Data scientist",
      tagline: "Turning messy data into decisions people trust.",
      availability: "Open to work",
    },
  },
  {
    id: "pm",
    label: "Product Manager",
    icon: "Kanban",
    description: "Impact-first layout that frames every project as an outcome.",
    template: "bento",
    themePresetId: "arctic",
    headingFont: "Plus Jakarta Sans",
    bodyFont: "Inter",
    sections: ["hero", "stats", "about", "experience", "projects", "skills", "testimonials", "contact"],
    profile: {
      headline: "Senior Product Manager",
      tagline: "0→1 products, and the unglamorous work that makes them stick.",
      availability: "Open to work",
    },
  },
  {
    id: "freelancer",
    label: "Freelancer",
    icon: "Rocket",
    description: "A page built to convert — services, proof and a clear next step.",
    template: "onepage",
    themePresetId: "cocoa",
    headingFont: "Outfit",
    bodyFont: "Rubik",
    sections: ["hero", "services", "projects", "about", "testimonials", "pricing", "faq", "cta", "contact"],
    profile: {
      headline: "Freelance designer & developer",
      tagline: "One person, end to end, no handoffs.",
      availability: "Available from next month",
    },
  },
  {
    id: "hacker",
    label: "Security / DevOps",
    icon: "Terminal",
    description: "Terminal-styled page for people who live in the shell.",
    template: "terminal",
    themePresetId: "matrix",
    headingFont: "JetBrains Mono",
    bodyFont: "IBM Plex Mono",
    sections: ["hero", "about", "skills", "experience", "projects", "certifications", "contact"],
    profile: {
      headline: "Security engineer",
      tagline: "Breaking things carefully, then making them harder to break.",
      availability: "Open to work",
    },
  },
  {
    id: "accountant",
    label: "Accountant",
    icon: "Calculator",
    description: "Credentials, compliance work and the systems you know, laid out for finance hiring.",
    template: "classic",
    themePresetId: "slate",
    headingFont: "Manrope",
    bodyFont: "Open Sans",
    sections: ["hero", "about", "experience", "skills", "certifications", "education", "services", "contact"],
    profile: {
      headline: "Senior Accountant",
      tagline: "Clean books, closed on time, audited without surprises.",
      availability: "Open to work",
    },
  },
  {
    id: "ca",
    label: "Chartered Accountant",
    icon: "ScrollText",
    description: "Practice-focused layout leading with licence, specialisms and client services.",
    template: "tabbed",
    themePresetId: "royal",
    headingFont: "Libre Baskerville",
    bodyFont: "Lato",
    sections: ["hero", "about", "services", "certifications", "experience", "education", "faq", "testimonials", "contact"],
    profile: {
      headline: "Chartered Accountant (ACA)",
      tagline: "Audit, tax and advisory for owner-managed businesses.",
      availability: "Accepting new clients",
    },
  },
  {
    id: "financial-analyst",
    label: "Financial Analyst",
    icon: "ChartSpline",
    description: "Numbers-forward page where the impact of your analysis comes first.",
    template: "bento",
    themePresetId: "arctic",
    headingFont: "Plus Jakarta Sans",
    bodyFont: "Inter",
    sections: ["hero", "stats", "about", "experience", "skills", "projects", "certifications", "education", "contact"],
    profile: {
      headline: "Financial Analyst",
      tagline: "Forecasting, valuation and the models behind the decisions.",
      availability: "Open to work",
    },
  },
  {
    id: "hr",
    label: "HR / Recruiter",
    icon: "Users",
    description: "People-first layout with hiring outcomes and the teams you have built.",
    template: "classic",
    themePresetId: "bubblegum",
    headingFont: "Figtree",
    bodyFont: "Nunito",
    sections: ["hero", "about", "stats", "experience", "skills", "services", "testimonials", "education", "contact"],
    profile: {
      headline: "Talent Partner",
      tagline: "Hiring that sticks - better loops, better offers, better retention.",
      availability: "Open to work",
    },
  },
  {
    id: "sales",
    label: "Sales / Business Dev",
    icon: "TrendingUp",
    description: "Quota attainment and named accounts up front, because that is what gets read.",
    template: "bento",
    themePresetId: "sunset",
    headingFont: "Sora",
    bodyFont: "Inter",
    sections: ["hero", "stats", "experience", "about", "clients", "skills", "testimonials", "contact"],
    profile: {
      headline: "Enterprise Account Executive",
      tagline: "Consultative selling into regulated industries.",
      availability: "Open to work",
    },
  },
  {
    id: "civil-engineer",
    label: "Civil Engineer",
    icon: "HardHat",
    description: "Project-led layout for site, structural and infrastructure work.",
    template: "timeline",
    themePresetId: "sand",
    headingFont: "Archivo Black",
    bodyFont: "Work Sans",
    sections: ["hero", "about", "projects", "experience", "certifications", "skills", "education", "contact"],
    profile: {
      headline: "Civil Engineer",
      tagline: "Infrastructure delivered on programme and within tolerance.",
      availability: "Open to work",
    },
  },
  {
    id: "nurse",
    label: "Nurse / Allied Health",
    icon: "HeartPulse",
    description: "Licensure, clinical settings and specialisms, clearly separated.",
    template: "tabbed",
    themePresetId: "arctic",
    headingFont: "Manrope",
    bodyFont: "Open Sans",
    sections: ["hero", "about", "certifications", "experience", "skills", "education", "languages", "contact"],
    profile: {
      headline: "Registered Nurse, Critical Care",
      tagline: "Ten years at the bedside, and still learning.",
      availability: "Open to work",
    },
  },
  {
    id: "operations",
    label: "Operations / Supply Chain",
    icon: "Truck",
    description: "Process and cost-savings layout built around measurable improvements.",
    template: "bento",
    themePresetId: "slate",
    headingFont: "Manrope",
    bodyFont: "Inter",
    sections: ["hero", "stats", "about", "experience", "projects", "skills", "certifications", "education", "contact"],
    profile: {
      headline: "Operations Manager",
      tagline: "Taking cost and chaos out of the supply chain.",
      availability: "Open to work",
    },
  },
  {
    id: "blank",
    label: "Start blank",
    icon: "FilePlus2",
    description: "Just a hero and a contact section. Build it up your own way.",
    template: "classic",
    themePresetId: "mono",
    headingFont: "Inter",
    bodyFont: "Inter",
    sections: ["hero", "contact"],
    profile: { headline: "", tagline: "", availability: "" },
  },
];

export const PRESETS_BY_ID = new Map(PRESETS.map((p) => [p.id, p]));
